### ISSUE TITLE
OrespawnMC github

### ISSUE THREAD

**Issue by KingOfTheGamesYT** [ShrekLeaker/ShrekLeaker#1]
The repository for OrespawnMC was taken down

**Comment by ShrekLeaker** [comment]
Yes I know, I will have a new one up soon.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ShrekLeaker** [comment]
New Repo is here >>> [https://github.com/ShrekLeaker/OreSpawnMC-1](https://github.com/ShrekLeaker/OreSpawnMC-1)
